#!/usr/bin/env Rscript

library(ggplot2)
library(grid)

# Configuration and exported data ----------------------------------------------

DATA_FILE <- "data/band_decay_data.R"
PALETTE_FILE <- "data/palette.R"
OUTPUT_FILE <- "plots/band_decay_90pct_r.png"
LEGEND_SEROTYPES <- c(
  "ST512-KL107",
  "ST147-KL64",
  "ST258-KL106",
  "ST11-KL24",
  "ST307-KL102",
  "ST101-KL17",
  "ST395-KL2",
  "ST258-KL107",
  "ST405-KL151",
  "ST15-KL112",
  "ST11-KL105",
  "ST147-KL107",
  "ST15-KL24",
  "ST231-KL51",
  "ST39-KL23",
  "ST392-KL27"
)

load_r_object <- function(data_file, object_name) {
  data_environment <- new.env(parent = baseenv())
  sys.source(data_file, envir = data_environment)
  data_environment[[object_name]]
}

# Both files are generated by update_fitted_country_curves_data.py.
curve_data <- load_r_object(DATA_FILE, "curve_data")
palette_data <- load_r_object(PALETTE_FILE, "palette_data")
band_data <- curve_data$band_decay
entity_order <- band_data$entity_order
entities <- band_data$entities[entity_order]
display_columns <- band_data$display_columns
plot_config <- band_data$plot
serotype_colors <- palette_data$serotype_colors[display_columns]

# NULL selects every displayed serotype for the legend.
if (!is.null(LEGEND_SEROTYPES)) {
  LEGEND_SEROTYPES <- unique(trimws(as.character(LEGEND_SEROTYPES)))
  LEGEND_SEROTYPES <- LEGEND_SEROTYPES[nzchar(LEGEND_SEROTYPES)]
  unknown_serotypes <- setdiff(LEGEND_SEROTYPES, display_columns)
  if (length(unknown_serotypes) > 0L) {
    warning(sprintf("Legend serotypes are not in the exported display columns and will be omitted: %s", paste(unknown_serotypes, collapse = ", ")))
  }
}
legend_serotypes <- if (is.null(LEGEND_SEROTYPES)) display_columns else LEGEND_SEROTYPES[LEGEND_SEROTYPES %in% display_columns]

# Data preparation and labels --------------------------------------------------

format_count <- function(values) {
  formatC(round(values), format = "d", big.mark = ",")
}

entity_label <- function(entity_name) {
  if (entity_name == "GLOBAL") "European aggregate" else entity_name
}

strike_text <- function(value) {
  paste0(strsplit(as.character(value), "", fixed = TRUE)[[1]], "\u0336", collapse = "")
}

entity_frame <- function(entity_name) {
  entity <- band_data$entities[[entity_name]]
  years <- as.numeric(entity$display_years)
  data.frame(
    entity = rep(entity_name, length(years) * length(display_columns)),
    year = rep(years, times = length(display_columns)),
    group = factor(rep(display_columns, each = length(years)), levels = display_columns),
    count = as.numeric(unlist(entity$grouped_counts[display_columns], use.names = FALSE)),
    share = as.numeric(unlist(entity$grouped_proportions[display_columns], use.names = FALSE))
  )
}

masked_years <- function(entity) {
  sort(unique(c(as.numeric(entity$excluded_years), as.numeric(entity$missing_years))))
}

stack_bounds <- function(plot_data, value_column) {
  # Stack in exported serotype order, shared by the absolute and relative panels.
  plot_data$ymin <- 0
  plot_data$ymax <- 0
  for (year in unique(plot_data$year)) {
    indices <- which(plot_data$year == year)
    upper <- cumsum(plot_data[[value_column]][indices])
    plot_data$ymin[indices] <- c(0, head(upper, -1L))
    plot_data$ymax[indices] <- upper
  }
  plot_data
}

# Panel styling and overlays ---------------------------------------------------

year_hatch_grob <- function() {
  gTree(hatch = plot_config$excluded_year_hatch, alpha = plot_config$excluded_year_alpha, cl = "year_hatch")
}

makeContent.year_hatch <- function(grob) {
  # Resolve physical spacing at draw time and align hatch strokes across panels.
  width <- convertWidth(unit(1, "npc"), "in", valueOnly = TRUE)
  height <- convertHeight(unit(1, "npc"), "in", valueOnly = TRUE)
  origin <- deviceLoc(unit(0, "npc"), unit(0, "npc"), valueOnly = TRUE)
  symbols <- strsplit(grob$hatch, "", fixed = TRUE)[[1]]
  strokes <- lapply(c(1, -1), function(direction) {
    repeats <- sum(symbols %in% c(if (direction == 1) "/" else "\\", "x", "X"))
    if (repeats == 0L) return(nullGrob())
    spacing <- 2 / (6 * repeats)
    phase <- (if (direction == 1) origin$x - origin$y else -origin$x - origin$y - width) %% spacing
    offsets <- seq(floor((-width - phase) / spacing), ceiling((height - phase) / spacing)) * spacing + phase
    x_start <- pmax(0, -offsets)
    x_end <- pmin(width, height - offsets)
    visible <- x_start < x_end
    segmentsGrob(
      x0 = unit(if (direction == 1) x_start[visible] else width - x_start[visible], "in"),
      x1 = unit(if (direction == 1) x_end[visible] else width - x_end[visible], "in"),
      y0 = unit((x_start + offsets)[visible], "in"),
      y1 = unit((x_end + offsets)[visible], "in"),
      gp = gpar(col = "#666666", alpha = grob$alpha, lwd = 4 / 3, lineend = "butt")
    )
  })
  setChildren(grob, do.call(gList, c(list(
    rectGrob(gp = gpar(fill = "#b0b0b0", col = NA, alpha = grob$alpha))
  ), strokes)))
}

base_plot_theme <- theme_minimal(base_size = 9, base_family = "sans") +
  theme(
    panel.grid.minor = element_blank(),
    panel.grid.major = element_line(color = "#e8ecf0", linewidth = 0.25),
    panel.grid.major.x = element_blank(),
    legend.position = "none",
    axis.title = element_text(color = "#475569", size = 9),
    axis.text = element_text(color = "#475569", size = 8),
    axis.text.x = element_text(size = 9, angle = 45, hjust = 1, vjust = 1, margin = margin(t = 4)),
    axis.line.x = element_line(color = "#aeb8c4", linewidth = 0.25),
    axis.ticks.x = element_line(color = "#aeb8c4", linewidth = 0.25),
    axis.ticks.length = unit(2, "pt"),
    plot.title = element_text(face = "bold", size = 11, color = "#1e293b", margin = margin(b = 9)),
    plot.margin = margin(6, 10, 8, 6)
  )

add_count_labels <- function(plot, plot_data, y_limit) {
  if (length(unique(plot_data$year)) > plot_config$count_label_max_years) return(plot)
  totals <- aggregate(count ~ year, plot_data, sum)
  cutoff <- plot_config$count_label_max_y_fraction * y_limit
  labels_data <- totals[totals$count > 0 & totals$count <= cutoff, , drop = FALSE]
  labels_data$label <- format_count(labels_data$count)
  labels_data$y <- labels_data$count + 0.015 * y_limit
  plot + geom_text(
    data = labels_data, aes(x = year, y = y, label = label), inherit.aes = FALSE,
    size = 2.1, color = "#333333", vjust = 0
  )
}

# Abundance and decay panels ---------------------------------------------------

build_stack_plot <- function(entity_name, plot_data, relative, show_title, show_y_label, show_x_label, absolute_ylim) {
  entity <- band_data$entities[[entity_name]]
  years <- sort(unique(plot_data$year))
  marked <- masked_years(entity)
  value_column <- if (relative) "share" else "count"
  y_limit <- if (relative) 1 else absolute_ylim * 1.04
  if (y_limit <= 0) y_limit <- 1
  labels <- as.character(years)
  if (isTRUE(plot_config$strike_excluded_year_labels)) {
    labels[years %in% marked] <- vapply(years[years %in% marked], strike_text, character(1))
  }
  panel_labels <- labs(
    title = if (show_title) paste(if (relative) "Relative" else "Absolute", "abundance"),
    x = if (show_x_label) "Collection year",
    y = if (show_y_label) if (relative) "Share" else "Count"
  )

  if (length(years) == 0L) {
    return(
      ggplot() + annotate("text", x = 0.5, y = 0.5, label = "No data", color = "#555555") +
        xlim(0, 1) + ylim(0, 1) +
        panel_labels + base_plot_theme
    )
  }

  plot_data <- stack_bounds(plot_data, value_column)
  plot <- ggplot(plot_data, aes(x = year, ymin = ymin, ymax = ymax, fill = group, group = group)) +
    geom_ribbon(stat = "identity", color = "white", linewidth = 0.14, outline.type = "full") +
    scale_fill_manual(values = serotype_colors, limits = display_columns, drop = FALSE) +
    scale_x_continuous(breaks = years, labels = labels, limits = c(min(years) - 0.5, max(years) + 0.5), expand = c(0, 0)) +
    coord_cartesian(ylim = c(0, y_limit), expand = FALSE) +
    panel_labels + base_plot_theme

  if (relative) {
    plot <- plot + scale_y_continuous(breaks = seq(0, 1, by = 0.25), labels = function(values) paste0(round(values * 100), "%"))
  } else {
    plot <- plot + scale_y_continuous(
      breaks = pretty(c(0, y_limit), n = if (show_title) 5 else 2), labels = format_count
    )
    plot <- add_count_labels(plot, plot_data, y_limit)
  }

  for (year in marked) {
    plot <- plot + annotation_custom(
      year_hatch_grob(),
      xmin = year - 0.5, xmax = year + 0.5, ymin = 0, ymax = y_limit
    )
  }
  plot
}

build_decay_plot <- function(entity_name, show_title, show_y_label, show_x_label) {
  entity <- band_data$entities[[entity_name]]
  decay <- entity$decay
  observed <- data.frame(lag = as.numeric(decay$lag), similarity = as.numeric(decay$similarity))
  xmax <- max(1, observed$lag)
  title <- if (show_title) "Morisita–Horn decay" else NULL
  y_label <- if (show_y_label) "Similarity (y0-normalized fit)" else NULL
  plot <- ggplot(observed, aes(x = lag, y = similarity)) +
    geom_point(size = 1.8, alpha = 0.65, color = "#222222", stroke = 0) +
    scale_x_continuous(breaks = seq(0, xmax, by = max(1, floor(xmax / 5))), limits = c(0, xmax * 1.04), expand = c(0, 0)) +
    scale_y_continuous(breaks = if (show_title) seq(0, 1, by = 0.2) else c(0, 0.5, 1)) +
    labs(title = title, x = if (show_x_label) "Year lag" else NULL, y = y_label) +
    base_plot_theme +
    theme(axis.text.x = element_text(angle = 0, hjust = 0.5), panel.grid.major.x = element_line(color = "#f0f2f5", linewidth = 0.25))

  fit <- decay$fit
  if (is.null(fit)) {
    return(plot + coord_cartesian(ylim = c(0, 1.02)) + annotate(
      "text", x = xmax / 2, y = 0.5, label = "Not fit\n< 3 lag pairs", color = "#555555", size = 2.7
    ))
  }
  fit_data <- data.frame(
    lag = fit$query, median = fit$median, lower = fit$lower, upper = fit$upper
  )
  upper_limit <- max(c(1.02, observed$similarity, fit_data$upper), na.rm = TRUE)
  lower_limit <- min(c(0, observed$similarity, fit_data$lower), na.rm = TRUE)
  plotted_upper <- upper_limit * 1.05
  # The export supplies normalized curves, but the table retains raw fit parameters.
  annotation <- sprintf("y0=%.2f, b=%.2f, c/y0=%.2f", 1, fit$b, fit$c / fit$y0)
  if (!is.null(fit$sigma)) annotation <- paste0(annotation, sprintf(", sigma=%.2f", fit$sigma))
  plot +
    geom_ribbon(
      data = fit_data, aes(x = lag, ymin = lower, ymax = upper), inherit.aes = FALSE,
      fill = "#4c78a8", alpha = 0.22, color = NA
    ) +
    geom_line(
      data = fit_data, aes(x = lag, y = median), inherit.aes = FALSE, color = "#1f4e79", linewidth = 0.7
    ) +
    coord_cartesian(ylim = c(lower_limit, plotted_upper)) +
    annotate(
      "text", x = xmax * 0.03, y = lower_limit + 0.05 * (plotted_upper - lower_limit),
      label = annotation, hjust = 0, vjust = 0, size = 2.3, color = "#333333"
    )
}

# Legend and parameter table ---------------------------------------------------

make_legend_grob <- function(labels, colors, max_labels, columns = 7L) {
  labels <- labels[seq_len(min(length(labels), max_labels))]
  if (length(labels) == 0L) return(nullGrob())
  colors <- unname(colors[labels])
  columns <- min(columns, length(labels))
  rows <- ceiling(length(labels) / columns)
  legend <- gtable::gtable(
    widths = rep(unit.c(unit(0.24, "in"), unit(1, "null")), columns),
    heights = unit(c(0.32, rep(0.20, rows)), "in")
  )
  heading <- textGrob(
    "MLST-CPS types", x = 0, just = "left", gp = gpar(fontsize = 10, fontface = "bold", col = "#1e293b")
  )
  legend <- gtable::gtable_add_grob(legend, heading, t = 1, l = 1, b = 1, r = columns * 2)
  for (index in seq_along(labels)) {
    row <- (index - 1L) %% rows + 2L
    column <- ((index - 1L) %/% rows) * 2L + 1L
    swatch <- rectGrob(
      x = 0, just = "left", width = unit(0.18, "in"), height = unit(0.085, "in"),
      gp = gpar(fill = colors[index], col = NA)
    )
    label <- textGrob(labels[index], x = 0, just = "left", gp = gpar(fontsize = 7.5, col = "#475569"))
    legend <- gtable::gtable_add_grob(legend, swatch, t = row, l = column, b = row, r = column)
    legend <- gtable::gtable_add_grob(legend, label, t = row, l = column + 1L, b = row, r = column + 1L)
  }
  legend
}

format_table_number <- function(value) {
  if (is.null(value) || length(value) == 0L || is.na(value)) "" else sprintf("%.2f", value)
}

make_parameter_table <- function() {
  include_sigma <- any(vapply(entity_order, function(name) !is.null(band_data$entities[[name]]$decay$fit$sigma), logical(1)))
  headers <- c("Country", "n", "y0", "b", "c")
  if (include_sigma) headers <- c(headers, "sigma")
  rows <- lapply(seq_along(entity_order), function(index) {
    entity_name <- entity_order[index]
    entity <- band_data$entities[[entity_name]]
    fit <- entity$decay$fit
    label <- if (index == 1L) entity_label(entity_name) else entity_name
    values <- c(
      label, format_count(entity$analysis_total),
      if (is.null(fit)) "not fit" else format_table_number(fit$y0),
      format_table_number(fit$b), format_table_number(fit$c)
    )
    if (include_sigma) values <- c(values, format_table_number(fit$sigma))
    values
  })
  rbind(headers, do.call(rbind, rows))
}

draw_parameter_table <- function(cells) {
  row_count <- nrow(cells)
  column_count <- ncol(cells)
  column_widths <- c(0.38, rep(0.62 / (column_count - 1L), column_count - 1L))
  column_edges <- c(0, cumsum(column_widths))
  for (row in seq_len(row_count)) {
    y <- 1 - (row - 0.5) / row_count
    grid.rect(
      y = y, height = 1 / row_count,
      gp = gpar(fill = if (row == 1L) "#eaf0f5" else if (row %% 2L == 0L) "#f7f9fb" else "white", col = NA)
    )
    for (column in seq_len(column_count)) {
      grid.text(
        cells[row, column],
        x = if (column == 1L) 0.02 else column_edges[column] + column_widths[column] / 2,
        y = y,
        just = if (column == 1L) "left" else "centre",
        gp = gpar(fontsize = 8, col = "#475569", fontface = if (row == 1L) "bold" else "plain")
      )
    }
  }
}

# Figure assembly -------------------------------------------------------------

build_plot_rows <- function(entity_frames, absolute_ylim) {
  lapply(seq_along(entity_order), function(index) {
    entity_name <- entity_order[index]
    plot_data <- entity_frames[[index]]
    main_row <- index == 1L
    last_row <- index == length(entity_order)
    lapply(list(
      build_stack_plot(
        entity_name, plot_data, relative = TRUE, show_title = main_row,
        show_y_label = main_row, show_x_label = last_row, absolute_ylim = absolute_ylim
      ),
      build_stack_plot(
        entity_name, plot_data, relative = FALSE, show_title = main_row,
        show_y_label = main_row, show_x_label = last_row, absolute_ylim = absolute_ylim
      ),
      build_decay_plot(entity_name, show_title = main_row, show_y_label = main_row, show_x_label = last_row)
    ), ggplotGrob)
  })
}

align_plot_rows <- function(plot_rows) {
  # Match axes within columns and titles within rows before allocating panel space.
  for (column in seq_len(3L)) {
    widths <- do.call(unit.pmax, lapply(plot_rows, function(row) row[[column]]$widths))
    for (index in seq_along(plot_rows)) plot_rows[[index]][[column]]$widths <- widths
  }
  fixed_heights <- numeric(length(plot_rows))
  for (index in seq_along(plot_rows)) {
    heights <- do.call(unit.pmax, lapply(plot_rows[[index]], function(grob) grob$heights))
    row_grob <- plot_rows[[index]][[1]]
    panel_row <- row_grob$layout$t[row_grob$layout$name == "panel"]
    fixed_heights[index] <- convertHeight(sum(heights[-panel_row]), "in", valueOnly = TRUE)
    for (column in seq_len(3L)) plot_rows[[index]][[column]]$heights <- heights
  }
  list(plots = plot_rows, fixed_heights = fixed_heights)
}

draw_plot_rows <- function(plot_rows, panel_heights) {
  for (index in seq_along(entity_order)) {
    for (column in seq_len(3L)) {
      pushViewport(viewport(layout.pos.row = index + 1L, layout.pos.col = column + 1L, clip = "on"))
      grid.draw(plot_rows[[index]][[column]])
      upViewport()
    }
    row_grob <- plot_rows[[index]][[1]]
    panel_row <- row_grob$layout$t[row_grob$layout$name == "panel"]
    label_y <- unit(1, "npc") - sum(row_grob$heights[seq_len(panel_row - 1L)]) - unit(panel_heights[index] / 2, "in")
    pushViewport(viewport(layout.pos.row = index + 1L, layout.pos.col = 1L))
    grid.text(
      entity_label(entity_order[index]), y = label_y, rot = 90,
      gp = gpar(fontsize = 9, fontface = "bold", col = "#334155")
    )
    upViewport()
  }
}

draw_footer <- function(legend_grob, table_cells, footer_height) {
  pushViewport(viewport(layout.pos.row = length(entity_order) + 2L, layout.pos.col = 1:4))
  grid.lines(x = c(0, 1), y = c(0.98, 0.98), gp = gpar(col = "#dce3ea", lwd = 0.7))
  pushViewport(viewport(y = unit(1, "npc") - unit(0.17, "in"), height = unit(0.2, "in")))
  pushViewport(viewport(x = unit(0.10, "in"), width = unit(0.18, "in"), height = unit(0.10, "in")))
  grid.draw(year_hatch_grob())
  upViewport()
  grid.text(
    "Hatched years: excluded",
    x = unit(0.25, "in"), just = "left", gp = gpar(fontsize = 8, col = "#64748b")
  )
  grid.text(
    sprintf("Decay: %s fit and %.0f%% posterior interval", plot_config$fit_summary, 100 * plot_config$confidence_level),
    x = 1, just = "right", gp = gpar(fontsize = 8, col = "#64748b")
  )
  upViewport()

  pushViewport(viewport(
    y = 0, height = unit(footer_height - 0.4, "in"), just = "bottom",
    layout = grid.layout(1, 3, widths = unit.c(unit(1, "null"), unit(0.35, "in"), unit(5.7, "in")))
  ))
  pushViewport(viewport(layout.pos.row = 1, layout.pos.col = 1))
  pushViewport(viewport(y = 1, height = sum(legend_grob$heights), just = "top"))
  grid.draw(legend_grob)
  upViewport(2)
  pushViewport(viewport(layout.pos.row = 1, layout.pos.col = 3))
  grid.text(
    "Fit parameters", x = 0, y = unit(1, "npc") - unit(0.16, "in"), just = "left",
    gp = gpar(fontsize = 10, fontface = "bold", col = "#1e293b")
  )
  pushViewport(viewport(
    y = unit(1, "npc") - unit(0.32, "in"), height = unit(nrow(table_cells) * 0.20, "in"), just = "top"
  ))
  draw_parameter_table(table_cells)
  upViewport(4)
}

render_band_decay <- function(output_file) {
  entity_frames <- lapply(entity_order, entity_frame)
  absolute_ylim <- max(vapply(entity_frames, function(counts) {
    if (nrow(counts) == 0L) 0 else max(tapply(counts$count, counts$year, sum))
  }, numeric(1)))
  if (absolute_ylim <= 0) absolute_ylim <- 1

  legend_labels <- if (is.null(LEGEND_SEROTYPES)) {
    display_columns[vapply(display_columns, function(label) {
      any(vapply(entities, function(entity) sum(entity$grouped_counts[[label]]) > 0, logical(1)))
    }, logical(1))]
  } else {
    legend_serotypes
  }
  legend_grob <- make_legend_grob(legend_labels, serotype_colors, plot_config$max_legend_labels)
  table_cells <- make_parameter_table()
  legend_rows <- ceiling(min(length(legend_labels), plot_config$max_legend_labels) / 7)
  footer_height <- max(2.6, 0.8 + nrow(table_cells) * 0.20, 0.8 + legend_rows * 0.20)
  figure_width <- 18
  figure_height <- max(8, 4.2 + 1.65 * (length(entity_order) - 1L) + footer_height + 0.4)

  output_directory <- dirname(output_file)
  if (!dir.exists(output_directory)) dir.create(output_directory, recursive = TRUE)
  png(output_file, width = figure_width, height = figure_height, units = "in", res = 300, bg = "white")
  on.exit(dev.off())

  aligned <- align_plot_rows(build_plot_rows(entity_frames, absolute_ylim))
  # Reserve space for axes and the footer; give the aggregate panel extra height.
  panel_ratios <- c(2.4, rep(1, length(entity_order) - 1L))
  available_height <- figure_height - 0.5 - 0.9 - footer_height - sum(aligned$fixed_heights)
  panel_heights <- available_height * panel_ratios / sum(panel_ratios)
  layout <- grid.layout(
    nrow = length(entity_order) + 2L,
    ncol = 4L,
    widths = unit.c(unit(0.4, "in"), unit(c(1.35, 1.35, 1.5), "null")),
    heights = unit(c(0.9, aligned$fixed_heights + panel_heights, footer_height), "in")
  )
  grid.newpage()
  pushViewport(viewport(width = unit(figure_width - 0.5, "in"), height = unit(figure_height - 0.5, "in"), layout = layout))
  pushViewport(viewport(layout.pos.row = 1, layout.pos.col = 1:4))
  grid.text(
    "Serotype composition and temporal similarity", x = 0, y = 0.78, just = "left",
    gp = gpar(fontsize = 19, fontface = "bold", col = "#172b40")
  )
  upViewport()
  draw_plot_rows(aligned$plots, panel_heights)
  draw_footer(legend_grob, table_cells, footer_height)
  upViewport()
}

render_band_decay(OUTPUT_FILE)
cat(sprintf("Wrote %s\n", OUTPUT_FILE))
